# Generated by Django 5.1.4 on 2024-12-14 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_publication', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('exemplaires', models.PositiveIntegerField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auteurs.auteur')),
            ],
        ),
    ]
