# Generated by Django 5.1.4 on 2024-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article_related_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_description',
            field=models.TextField(blank=True, help_text='Detailed preparation steps'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.DeleteModel(
            name='PreparationStep',
        ),
    ]
