# Generated by Django 5.1.4 on 2024-12-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('location', models.CharField(max_length=150, verbose_name='Localisation')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
            ],
        ),
    ]
